const N5Array = [
  {
    name: "浴びる",
    dictionaryForm: "あびる",
    pastForm: "あびた",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Ichidan",
  },
  {
    name: "上げる",
    dictionaryForm: "あげる",
    pastForm: "あげた",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Ichidan",
  },
  {
    name: "開ける",
    dictionaryForm: "あける",
    pastForm: "あけた",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Ichidan",
  },
  {
    name: "開く",
    dictionaryForm: "あく",
    pastForm: "あいた",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Godan",
  },
  {
    name: "洗う",
    dictionaryForm: "あらう",
    pastForm: "あらった",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Godan",
  },
];

const N4Array = [
  {
    name: "会う",
    dictionaryForm: "あう",
    pastForm: "あった",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Godan",
  },
  {
    name: "合う",
    dictionaryForm: "あう",
    pastForm: "あった",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Godan",
  },
  {
    name: "上がる",
    dictionaryForm: "上がる",
    pastForm: "あがった",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Godan",
  },
  {
    name: "開ける",
    dictionaryForm: "あける",
    pastForm: "あけた",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Ichidan",
  },
  {
    name: "上げる",
    dictionaryForm: "あげる",
    pastForm: "あげた",
    potentialForm: "",
    passiveForm: "",
    causativeForm: "",
    teForm: "",
    masuForm: "",
    volitionalForm: "",
    imperitiveForm: "",
    verbType: "Ichidan",
  },
];

const N3Array = [];

const N2Array = [];

const N1Array = [];

const JLPTData = {
  N5: N5Array,
  N4: N4Array,
  N3: N3Array,
  N2: N2Array,
  N1: N1Array,
};

export default JLPTData;
